cexpcov.c File Reference
#include <R.h>
#include <Rmath.h>
#include <Rinternals.h>
#include `party.h`
Functions
SEXP kronecker (SEXP A, SEXP B)
void setAllZero (SEXP A)
SEXP ec (SEXP Weights, SEXP Scores, SEXP cweights)
SEXP evS (SEXP Scores, SEXP cweights)
SEXP evL (SEXP Weights, SEXP Scores, SEXP cweights, SEXP evSans)
SEXP ev (SEXP Weights, SEXP Scores, SEXP cweights)
Function Documentation
SEXP ec (SEXP Weights, SEXP Scores, SEXP cweights)
Definition at line 81 of file cexpcov.c.
References aindx(), error, kronecker(), and setAllZero().
SEXP ev (SEXP Weights, SEXP Scores, SEXP cweights)
Definition at line 455 of file cexpcov.c.
References evL(), and evS().
SEXP evL (SEXP Weights, SEXP Scores, SEXP cweights, SEXP evSans)
Definition at line 348 of file cexpcov.c.
References aindx(), error, and setAllZero().
Referenced by ev().
SEXP evS (SEXP Scores, SEXP cweights)
Definition at line 266 of file cexpcov.c.
References aindx(), error, and setAllZero().
Referenced by ev().
SEXP kronecker (SEXP A, SEXP B)
Definition at line 7 of file cexpcov.c.
References aindx(), and error.
Referenced by ec().
void setAllZero (SEXP A)
Definition at line 68 of file cexpcov.c.
Referenced by ec(), evL(), and evS().