CIstuff.c File Reference
#include `PL2_common.h`
Functions
SEXP R_blocksetup (SEXP block)
void C_blockperm (SEXP blocksetup, int *ans)
SEXP R_blockperm (SEXP block)
SEXP R_MonteCarloIndependenceTest (SEXP x, SEXP y, SEXP block, SEXP B)
Detailed Description
Some additional functionality for package `ConditionalInference'
Author:
Author hothorn
Date:
Date 2005/06/09 12:21:38
Definition in file CIstuff.c.
Function Documentation
void C_blockperm (SEXP blocksetup, int * ans)
Block permutation
Parameters:
blocksetup an object as returned by function `R_blocksetup'
ans return value, the (block)-permutation of 1:n
Definition at line 66 of file CIstuff.c.
References C_SampleNoReplace().
Referenced by R_blockperm(), and R_MonteCarloIndependenceTest().
SEXP R_blockperm (SEXP block)
Definition at line 95 of file CIstuff.c.
References C_blockperm(), and R_blocksetup().
SEXP R_blocksetup (SEXP block)
Definition at line 12 of file CIstuff.c.
Referenced by R_blockperm(), and R_MonteCarloIndependenceTest().
SEXP R_MonteCarloIndependenceTest (SEXP x, SEXP y, SEXP block, SEXP B)
Definition at line 108 of file CIstuff.c.
References C_blockperm(), C_PermutedLinearStatistic(), ncol(), nrow(), and R_blocksetup().