Distributions.c File Reference
#include `party.h`
Functions
double C_quadformConditionalPvalue (const double tstat, const double df)
SEXP R_quadformConditionalPvalue (SEXP tstat, SEXP df)
double C_maxabsConditionalPvalue (const double tstat, const double *Sigma, const int pq, int *maxpts, double *releps, double *abseps, double *tol)
SEXP R_maxabsConditionalPvalue (SEXP tstat, SEXP Sigma, SEXP maxpts, SEXP releps, SEXP abseps, SEXP tol)
void C_MonteCarlo (double *criterion, SEXP learnsample, SEXP weights, SEXP fitmem, SEXP varctrl, SEXP gtctrl, double *ans_pvalues)
SEXP R_MonteCarlo (SEXP criterion, SEXP learnsample, SEXP weights, SEXP fitmem, SEXP varctrl, SEXP gtctrl)
Detailed Description
Conditional Distributions
Author:
Author hothorn
Date:
Date 2005/06/14 09:21:32
Definition in file Distributions.c.
Function Documentation
double C_maxabsConditionalPvalue (const double tstat, const double * Sigma, const int pq, int * maxpts, double * releps, double * abseps, double * tol)
Conditional asymptotic P-value of a maxabs-type test statistic
 Basically the functionality from package `mvtnorm'
Parameters:
tstat test statitstic
Sigma covariance matrix
pq nrow(Sigma)
maxpts number of Monte-Carlo steps
releps relative error
abseps absolute error
tol tolerance
Definition at line 52 of file Distributions.c.
References mvtdst.
Referenced by C_ConditionalPvalue(), and R_maxabsConditionalPvalue().
void C_MonteCarlo (double * criterion, SEXP learnsample, SEXP weights, SEXP fitmem, SEXP varctrl, SEXP gtctrl, double * ans_pvalues)
Monte-Carlo approximation to the conditional pvalues
Parameters:
criterion vector of node criteria for each input
learnsample an object of class `LearningSample'
weights case weights
fitmem an object of class `TreeFitMemory'
varctrl an object of class `VariableControl'
gtctrl an object of class `GlobalTestControl'
ans_pvalues return values; vector of adjusted pvalues
Definition at line 169 of file Distributions.c.
References C_max(), C_MLinearStatistic(), C_PermutedLinearStatistic(), C_SampleNoReplace(), C_TeststatCriterion(), get_Mscorematrix(), get_ninputs(), get_nobs(), get_nresample(), get_transformation(), get_varmemory(), get_varMmemory(), has_missings(), is_ordinal(), ncol(), PL2_expcovinfSym, PL2_inputsSym, PL2_linearstatisticSym, PL2_responsesSym, and PL2_sumweightsSym.
Referenced by C_GlobalTest(), and R_MonteCarlo().
double C_quadformConditionalPvalue (const double tstat, const double df)
Conditional asymptotic P-value of a quadratic form
Parameters:
tstat test statistic
df degree of freedom
Definition at line 18 of file Distributions.c.
Referenced by C_ConditionalPvalue(), and R_quadformConditionalPvalue().
SEXP R_maxabsConditionalPvalue (SEXP tstat, SEXP Sigma, SEXP maxpts, SEXP releps, SEXP abseps, SEXP tol)
R-interface to C_maxabsConditionalPvalue
Parameters:
tstat test statitstic
Sigma covariance matrix
maxpts number of Monte-Carlo steps
releps relative error
abseps absolute error
tol tolerance
Definition at line 142 of file Distributions.c.
References C_maxabsConditionalPvalue(), and nrow().
SEXP R_MonteCarlo (SEXP criterion, SEXP learnsample, SEXP weights, SEXP fitmem, SEXP varctrl, SEXP gtctrl)
R-interface to C_MonteCarlo
Parameters:
criterion vector of node criteria for each input
learnsample an object of class `LearningSample'
weights case weights
fitmem an object of class `TreeFitMemory'
varctrl an object of class `VariableControl'
gtctrl an object of class `GlobalTestControl'
Definition at line 275 of file Distributions.c.
References C_MonteCarlo(), and get_ninputs().
SEXP R_quadformConditionalPvalue (SEXP tstat, SEXP df)
R-interface to C_quadformConditionalPvalue
Parameters:
tstat test statitstic
df degree of freedom
Definition at line 29 of file Distributions.c.
References C_quadformConditionalPvalue().