mvt.f File Reference
Functions
subroutine MVTDST (N, NU, LOWER, UPPER, INFIN, CORREL, DELTA, MAXPTS, ABSEPS, RELEPS, ERROR, VALUE, INFORM)
subroutine MVSUBR (N, W, NF, F)
subroutine MVSPCL (ND, NU, A, B, DL, COV, INFI, SNU, VL, ER, INFORM)
subroutine MVVLSB (N, W, R, DL, INFI, A, B, COV, Y, DI, EI, ND, VALUE)
subroutine MVSORT (N, LOWER, UPPER, DELTA, CORREL, INFIN, Y, PIVOT, ND, A, B, DL, COV, INFI, INFORM)
DOUBLE PRECISION MVTDNS (NU, X)
subroutine MVLIMS (A, B, INFIN, LOWER, UPPER)
subroutine MVSSWP (X, Y)
subroutine MVSWAP (P, Q, A, B, D, INFIN, N, C)
DOUBLE PRECISION MVPHI (Z)
DOUBLE PRECISION MVPHNV (P)
DOUBLE PRECISION MVBVN (LOWER, UPPER, INFIN, CORREL)
DOUBLE PRECISION MVBVU (SH, SK, R)
DOUBLE PRECISION MVSTDT (NU, T)
DOUBLE PRECISION MVBVT (NU, LOWER, UPPER, INFIN, CORREL)
DOUBLE PRECISION MVBVTC (NU, L, U, INFIN, RHO)
double precision mvbvtl (nu, dh, dk, r)
DOUBLE PRECISION MVCHNV (N, P)
DOUBLE PRECISION MVCHNC (LKN, N, P, R)
subroutine MVKBRV (NDIM, MINVLS, MAXVLS, NF, FUNSUB, ABSEPS, RELEPS, ABSERR, FINEST, INFORM)
subroutine MVKRSV (NDIM, KL, VALUES, PRIME, VK, NF, FUNSUB, X, R, PR, FS)
DOUBLE PRECISION MVUNI ()
Function Documentation
DOUBLE PRECISION MVBVN (DOUBLE PRECISION,dimension(*) LOWER, DOUBLE PRECISION,dimension(*) UPPER, INTEGER,dimension(*) INFIN, DOUBLE PRECISION CORREL)
Definition at line 659 of file mvt.f.
References MVBVU().
Referenced by MVBVT().
DOUBLE PRECISION MVBVT (INTEGER NU, DOUBLE PRECISION,dimension(*) LOWER, DOUBLE PRECISION,dimension(*) UPPER, INTEGER,dimension(*) INFIN, DOUBLE PRECISION CORREL)
Definition at line 858 of file mvt.f.
References MVBVN().
Referenced by MVBVTC(), and MVSPCL().
DOUBLE PRECISION MVBVTC (INTEGER NU, DOUBLE PRECISION,dimension(*) L, DOUBLE PRECISION,dimension(*) U, INTEGER,dimension(*) INFIN, DOUBLE PRECISION RHO)
Definition at line 909 of file mvt.f.
References MVBVT().
double precision mvbvtl (integer nu, double precision dh, double precision dk, double precision r)
Definition at line 962 of file mvt.f.
DOUBLE PRECISION MVBVU (DOUBLE PRECISION SH, DOUBLE PRECISION SK, DOUBLE PRECISION R)
Definition at line 704 of file mvt.f.
References MVPHI().
Referenced by MVBVN().
DOUBLE PRECISION MVCHNC (DOUBLE PRECISION LKN, INTEGER N, DOUBLE PRECISION P, DOUBLE PRECISION R)
Definition at line 1104 of file mvt.f.
References MVPHI().
Referenced by MVCHNV().
DOUBLE PRECISION MVCHNV (INTEGER N, DOUBLE PRECISION P)
Definition at line 1054 of file mvt.f.
References MVCHNC(), and MVPHNV().
Referenced by MVSUBR().
subroutine MVKBRV (INTEGER NDIM, INTEGER MINVLS, INTEGER MAXVLS, INTEGER NF, FUNSUB, DOUBLE PRECISION ABSEPS, DOUBLE PRECISION RELEPS, DOUBLE PRECISION ABSERR, DOUBLE PRECISION,dimension(*) FINEST, INTEGER INFORM)
Definition at line 1170 of file mvt.f.
References MVKRSV().
Referenced by MVTDST().
subroutine MVKRSV (INTEGER NDIM, INTEGER KL, DOUBLE PRECISION,dimension(*) VALUES, INTEGER PRIME, DOUBLE PRECISION,dimension(*) VK, INTEGER NF, FUNSUB, DOUBLE PRECISION,dimension(*) X, DOUBLE PRECISION,dimension(*) R, INTEGER,dimension(*) PR, DOUBLE PRECISION,dimension(*) FS)
Definition at line 1443 of file mvt.f.
References MVUNI().
Referenced by MVKBRV().
subroutine MVLIMS (DOUBLE PRECISION A, DOUBLE PRECISION B, INTEGER INFIN, DOUBLE PRECISION LOWER, DOUBLE PRECISION UPPER)
Definition at line 451 of file mvt.f.
References MVPHI().
Referenced by MVSORT(), and MVVLSB().
DOUBLE PRECISION MVPHI (DOUBLE PRECISION Z)
Definition at line 500 of file mvt.f.
Referenced by MVBVU(), MVCHNC(), MVLIMS(), and MVSTDT().
DOUBLE PRECISION MVPHNV (P)
Definition at line 550 of file mvt.f.
Referenced by MVCHNV(), and MVVLSB().
subroutine MVSORT (INTEGER N, DOUBLE PRECISION,dimension(*) LOWER, DOUBLE PRECISION,dimension(*) UPPER, DOUBLE PRECISION,dimension(*) DELTA, DOUBLE PRECISION,dimension(*) CORREL, INTEGER,dimension(*) INFIN, DOUBLE PRECISION,dimension(*) Y, LOGICAL PIVOT, INTEGER ND, DOUBLE PRECISION,dimension(*) A, DOUBLE PRECISION,dimension(*) B, DOUBLE PRECISION,dimension(*) DL, DOUBLE PRECISION,dimension(*) COV, INTEGER,dimension(*) INFI, INTEGER INFORM)
Definition at line 246 of file mvt.f.
References MVLIMS(), MVSSWP(), MVSWAP(), and MVTDNS().
Referenced by MVSUBR().
subroutine MVSPCL (INTEGER ND, INTEGER NU, DOUBLE PRECISION,dimension(*) A, DOUBLE PRECISION,dimension(*) B, DOUBLE PRECISION,dimension(*) DL, DOUBLE PRECISION,dimension(*) COV, INTEGER,dimension(*) INFI, DOUBLE PRECISION SNU, DOUBLE PRECISION VL, DOUBLE PRECISION ER, INTEGER INFORM)
Definition at line 117 of file mvt.f.
References MVBVT(), and MVSTDT().
Referenced by MVSUBR().
subroutine MVSSWP (DOUBLE PRECISION X, DOUBLE PRECISION Y)
Definition at line 463 of file mvt.f.
Referenced by MVSORT(), and MVSWAP().
DOUBLE PRECISION MVSTDT (INTEGER NU, DOUBLE PRECISION T)
Definition at line 822 of file mvt.f.
References MVPHI().
Referenced by MVSPCL().
subroutine MVSUBR (INTEGER N, DOUBLE PRECISION,dimension(*) W, INTEGER NF, DOUBLE PRECISION,dimension(*) F)
Definition at line 84 of file mvt.f.
References MVCHNV(), MVSORT(), MVSPCL(), and MVVLSB().
Referenced by MVTDST().
subroutine MVSWAP (INTEGER P, INTEGER Q, DOUBLE PRECISION,dimension(*) A, DOUBLE PRECISION,dimension(*) B, DOUBLE PRECISION,dimension(*) D, INTEGER,dimension(*) INFIN, INTEGER N, DOUBLE PRECISION,dimension(*) C)
Definition at line 470 of file mvt.f.
References MVSSWP().
Referenced by MVSORT().
DOUBLE PRECISION MVTDNS (INTEGER NU, DOUBLE PRECISION X)
Definition at line 429 of file mvt.f.
Referenced by MVSORT().
subroutine MVTDST (INTEGER N, INTEGER NU, DOUBLE PRECISION,dimension(*) LOWER, DOUBLE PRECISION,dimension(*) UPPER, INTEGER,dimension(*) INFIN, DOUBLE PRECISION,dimension(*) CORREL, DOUBLE PRECISION,dimension(*) DELTA, INTEGER MAXPTS, DOUBLE PRECISION ABSEPS, DOUBLE PRECISION RELEPS, DOUBLE PRECISION ERROR, DOUBLE PRECISION VALUE, INTEGER INFORM)
Definition at line 4 of file mvt.f.
References MVKBRV(), and MVSUBR().
DOUBLE PRECISION MVUNI ()
Definition at line 1489 of file mvt.f.
References unifrnd().
Referenced by MVKRSV().
subroutine MVVLSB (INTEGER N, DOUBLE PRECISION,dimension(*) W, DOUBLE PRECISION R, DOUBLE PRECISION,dimension(*) DL, INTEGER,dimension(*) INFI, DOUBLE PRECISION,dimension(*) A, DOUBLE PRECISION,dimension(*) B, DOUBLE PRECISION,dimension(*) COV, DOUBLE PRECISION,dimension(*) Y, DOUBLE PRECISION DI, DOUBLE PRECISION EI, INTEGER ND, DOUBLE PRECISION VALUE)
Definition at line 194 of file mvt.f.
References MVLIMS(), and MVPHNV().
Referenced by MVSUBR().