Node.c File Reference
#include `party.h`
Functions
void C_prediction (const double *y, int n, int q, const double *weights, const double sweights, double *ans)
void C_Node (SEXP node, SEXP learnsample, SEXP weights, SEXP fitmem, SEXP controls, int TERMINAL, int depth)
SEXP R_Node (SEXP learnsample, SEXP weights, SEXP fitmem, SEXP controls)
Detailed Description
Node computations
Author:
Author hothorn
Date:
Date 2007-09-26 14:44:59 +0200 (Wed, 26 Sep 2007)
Definition in file Node.c.
Function Documentation
void C_Node (SEXP node, SEXP learnsample, SEXP weights, SEXP fitmem, SEXP controls, int TERMINAL, int depth)
The main function for all node computations
Parameters:
node an initialized node (an S3 object!)
learnsample an object of class `LearningSample'
weights case weights
fitmem an object of class `TreeFitMemory'
controls an object of class `TreeControl'
TERMINAL logical indicating if this node will be a terminal node
depth an integer giving the depth of the current node
Definition at line 49 of file Node.c.
References C_GlobalTest(), C_init_nominalsplit(), C_init_orderedsplit(), C_max(), C_prediction(), C_split(), C_splitcategorical(), C_standardize(), C_tempweights(), C_whichmax(), get_dimension(), get_gtctrl(), get_levels(), get_mincriterion(), get_minsplit(), get_ninputs(), get_nobs(), get_ordering(), get_predict_trafo(), get_savesplitstats(), get_splitctrl(), get_splitstatistics(), get_test_trafo(), get_tgctrl(), get_tol(), get_transformation(), get_varctrl(), get_variable(), get_varmemory(), has_missings(), is_nominal(), ncol(), PL2_covarianceSym, PL2_expcovinfSym, PL2_expectationSym, PL2_inputsSym, PL2_linearstatisticSym, PL2_linexpcov2sampleSym, PL2_responsesSym, PL2_sumweightsSym, S3_SUMWEIGHTS, S3get_criterion(), S3get_maxcriterion(), S3get_prediction(), S3get_primarysplit(), S3get_splitpoint(), S3get_splitstatistics(), S3get_table(), S3get_teststat(), S3set_nodeterminal(), and S3set_variableID().
Referenced by C_TreeGrow(), and R_Node().
void C_prediction (const double * y, int n, int q, const double * weights, const double sweights, double * ans)
Compute prediction of a node
Parameters:
y the response variable (raw numeric values or dummy encoded factor)
n number of observations
q number of columns of y
weights case weights
sweights sum of case weights
ans return value; the q-dimensional predictions
Definition at line 22 of file Node.c.
Referenced by C_Node().
SEXP R_Node (SEXP learnsample, SEXP weights, SEXP fitmem, SEXP controls)
R-interface to C_Node
Parameters:
learnsample an object of class `LearningSample'
weights case weights
fitmem an object of class `TreeFitMemory'
controls an object of class `TreeControl'
Definition at line 228 of file Node.c.
References C_init_node(), C_Node(), get_maxsurrogate(), get_ninputs(), get_nobs(), get_predict_trafo(), get_splitctrl(), ncol(), NODE_LENGTH, and PL2_responsesSym.