Predict.h File Reference
Functions
void C_splitnode (SEXP node, SEXP learnsample, SEXP control)
Function Documentation
void C_splitnode (SEXP node, SEXP learnsample, SEXP control)
Split a node according to a splitting rule
Parameters:
node the current node with primary split specified
learnsample learning sample
control an object of class `TreeControl'
Todo outplace the splitting since there are at least 3 functions with nearly identical code
Definition at line 21 of file Predict.c.
References C_init_node(), get_maxsurrogate(), get_missings(), get_ninputs(), get_nobs(), get_predict_trafo(), get_splitctrl(), get_variable(), has_missings(), i_in_set(), ncol(), NODE_LENGTH, PL2_inputsSym, PL2_responsesSym, S3_LEFT, S3_RIGHT, S3get_nodeweights(), S3get_primarysplit(), S3get_splitpoint(), S3get_variableID(), and S3is_ordered().
Referenced by C_TreeGrow().