RandomForest.c File Reference
#include `party.h`
Functions
SEXP R_Ensemble (SEXP learnsample, SEXP weights, SEXP bwhere, SEXP bweights, SEXP fitmem, SEXP controls)
Detailed Description
Random forest with conditional inference trees
Author:
Author hothorn
Date:
Date 2007-07-23 10:09:38 +0200 (Mon, 23 Jul 2007)
Definition in file RandomForest.c.
Function Documentation
SEXP R_Ensemble (SEXP learnsample, SEXP weights, SEXP bwhere, SEXP bweights, SEXP fitmem, SEXP controls)
An experimental implementation of random forest like algorithms
Parameters:
learnsample an object of class `LearningSample'
weights a vector of case weights
bwhere integer matrix (n x ntree) for terminal node numbers
bweights double matrix (n x ntree) for bootstrap case weights
fitmem an object of class `TreeFitMemory'
controls an object of class `TreeControl'
Definition at line 22 of file RandomForest.c.
References C_init_node(), C_remove_weights(), C_SampleSplitting(), C_TreeGrow(), get_fraction(), get_maxsurrogate(), get_ninputs(), get_nobs(), get_ntree(), get_predict_trafo(), get_replace(), get_splitctrl(), ncol(), NODE_LENGTH, PL2_responsesSym, and S3get_nodeweights().