S3Classes.c File Reference
#include `party.h`
Functions
void C_init_node (SEXP node, int nobs, int ninputs, int nsurr, int q)
void S3set_nodeID (SEXP node, int nodeID)
int S3get_nodeID (SEXP node)
SEXP S3get_nodeweights (SEXP node)
double S3get_sumweights (SEXP node)
SEXP S3get_teststat (SEXP node)
SEXP S3get_criterion (SEXP node)
SEXP S3get_maxcriterion (SEXP node)
void S3set_nodeterminal (SEXP node)
int S3get_nodeterminal (SEXP node)
SEXP S3get_primarysplit (SEXP node)
SEXP S3get_surrogatesplits (SEXP node)
SEXP S3get_prediction (SEXP node)
SEXP S3get_leftnode (SEXP node)
SEXP S3get_rightnode (SEXP node)
void C_init_orderedsplit (SEXP split, int nobs)
void C_init_nominalsplit (SEXP split, int nlevels, int nobs)
void S3set_variableID (SEXP split, int variableID)
int S3get_variableID (SEXP split)
int S3is_ordered (SEXP split)
void S3set_ordered (SEXP split)
void S3set_nominal (SEXP split)
int S3get_toleft (SEXP split)
void S3set_toleft (SEXP split, int left)
SEXP S3get_splitpoint (SEXP split)
SEXP S3get_splitstatistics (SEXP split)
SEXP S3get_table (SEXP split)
Detailed Description
S3 classes for dealing with nodes and splits
Author:
Author hothorn
Date:
Date 2007-07-23 09:44:00 +0200 (Mon, 23 Jul 2007)
Definition in file S3Classes.c.
Function Documentation
void C_init_node (SEXP node, int nobs, int ninputs, int nsurr, int q)
Definition at line 11 of file S3Classes.c.
References CRITERION_LENGTH, NODE_LENGTH, S3_CRITERION, S3_iCRITERION, S3_MAXCRITERION, S3_NODEID, S3_PREDICTION, S3_PSPLIT, S3_SSPLIT, S3_STATISTICS, S3_SUMWEIGHTS, S3_TERMINAL, S3_WEIGHTS, and SPLIT_LENGTH.
Referenced by C_splitnode(), R_Node(), and R_TreeGrow().
void C_init_nominalsplit (SEXP split, int nlevels, int nobs)
Definition at line 128 of file S3Classes.c.
References S3_ORDERED, S3_SPLITPOINT, S3_SPLITSTATISTICS, S3_TABLE, S3_TOLEFT, S3_VARIABLEID, and SPLIT_LENGTH.
Referenced by C_Node().
void C_init_orderedsplit (SEXP split, int nobs)
Definition at line 104 of file S3Classes.c.
References S3_ORDERED, S3_SPLITPOINT, S3_SPLITSTATISTICS, S3_TABLE, S3_TOLEFT, S3_VARIABLEID, and SPLIT_LENGTH.
Referenced by C_Node().
SEXP S3get_criterion (SEXP node)
Definition at line 68 of file S3Classes.c.
References S3_CRITERION, and S3_iCRITERION.
Referenced by C_Node().
SEXP S3get_leftnode (SEXP node)
Definition at line 96 of file S3Classes.c.
References S3_LEFT.
Referenced by C_get_node(), C_get_nodebynum(), C_remove_weights(), C_splitsurrogate(), and C_TreeGrow().
SEXP S3get_maxcriterion (SEXP node)
Definition at line 72 of file S3Classes.c.
References S3_CRITERION, and S3_MAXCRITERION.
Referenced by C_get_node(), and C_Node().
int S3get_nodeID (SEXP node)
Definition at line 47 of file S3Classes.c.
References S3_NODEID.
Referenced by C_get_nodebynum(), and C_get_nodeID().
int S3get_nodeterminal (SEXP node)
Definition at line 80 of file S3Classes.c.
References S3_TERMINAL.
Referenced by C_get_node(), C_get_nodebynum(), C_remove_weights(), and C_TreeGrow().
SEXP S3get_nodeweights (SEXP node)
Definition at line 51 of file S3Classes.c.
References S3_WEIGHTS.
Referenced by C_get_nodeweights(), C_splitnode(), C_splitsurrogate(), C_surrogates(), C_TreeGrow(), and R_TreeGrow().
SEXP S3get_prediction (SEXP node)
Definition at line 92 of file S3Classes.c.
References S3_PREDICTION.
Referenced by C_get_prediction(), C_getpredictions(), C_Node(), and R_predictRF_weights().
SEXP S3get_primarysplit (SEXP node)
Definition at line 84 of file S3Classes.c.
References S3_PSPLIT.
Referenced by C_get_node(), C_Node(), C_splitnode(), C_splitsurrogate(), and C_surrogates().
SEXP S3get_rightnode (SEXP node)
Definition at line 100 of file S3Classes.c.
References S3_RIGHT.
Referenced by C_get_node(), C_get_nodebynum(), C_remove_weights(), C_splitsurrogate(), and C_TreeGrow().
SEXP S3get_splitpoint (SEXP split)
Definition at line 179 of file S3Classes.c.
References S3_SPLITPOINT.
Referenced by C_get_node(), C_Node(), C_splitnode(), and C_splitsurrogate().
SEXP S3get_splitstatistics (SEXP split)
Definition at line 183 of file S3Classes.c.
References S3_SPLITSTATISTICS.
Referenced by C_Node().
double S3get_sumweights (SEXP node)
Definition at line 60 of file S3Classes.c.
References S3_SUMWEIGHTS.
Referenced by C_get_node().
SEXP S3get_surrogatesplits (SEXP node)
Definition at line 88 of file S3Classes.c.
References S3_SSPLIT.
Referenced by C_get_node(), C_splitsurrogate(), C_surrogates(), and R_surrogates().
SEXP S3get_table (SEXP split)
Definition at line 192 of file S3Classes.c.
References S3_TABLE.
Referenced by C_Node().
SEXP S3get_teststat (SEXP node)
Definition at line 64 of file S3Classes.c.
References S3_CRITERION, and S3_STATISTICS.
Referenced by C_Node().
int S3get_toleft (SEXP split)
Definition at line 170 of file S3Classes.c.
References S3_TOLEFT.
Referenced by C_get_node(), and C_splitsurrogate().
int S3get_variableID (SEXP split)
Definition at line 154 of file S3Classes.c.
References S3_VARIABLEID.
Referenced by C_get_node(), C_splitnode(), C_splitsurrogate(), and C_surrogates().
int S3is_ordered (SEXP split)
Definition at line 158 of file S3Classes.c.
References S3_ORDERED.
Referenced by C_get_node(), and C_splitnode().
void S3set_nodeID (SEXP node, int nodeID)
Definition at line 43 of file S3Classes.c.
References S3_NODEID.
Referenced by C_TreeGrow().
void S3set_nodeterminal (SEXP node)
Definition at line 76 of file S3Classes.c.
References S3_TERMINAL.
void S3set_nominal (SEXP split)
Definition at line 166 of file S3Classes.c.
References S3_ORDERED.
void S3set_ordered (SEXP split)
Definition at line 162 of file S3Classes.c.
References S3_ORDERED.
void S3set_toleft (SEXP split, int left)
Definition at line 174 of file S3Classes.c.
References S3_TOLEFT.
void S3set_variableID (SEXP split, int variableID)
Definition at line 150 of file S3Classes.c.
References S3_VARIABLEID.
Referenced by C_Node().