TreeGrow.c File Reference
#include `party.h`
Functions
void C_TreeGrow (SEXP node, SEXP learnsample, SEXP fitmem, SEXP controls, int *where, int *nodenum, int depth)
SEXP R_TreeGrow (SEXP learnsample, SEXP weights, SEXP fitmem, SEXP controls, SEXP where)
Detailed Description
The tree growing recursion
Author:
Author hothorn
Date:
Date 2007-07-23 09:44:00 +0200 (Mon, 23 Jul 2007)
Definition in file TreeGrow.c.
Function Documentation
void C_TreeGrow (SEXP node, SEXP learnsample, SEXP fitmem, SEXP controls, int * where, int * nodenum, int depth)
The main tree growing function, handles the recursion.
Parameters:
node a list representing the current node
learnsample an object of class `LearningSample'
fitmem an object of class `TreeFitMemory'
controls an object of class `TreeControl'
where a pointer to an integer vector of n-elements
nodenum a pointer to a integer vector of length 1
depth an integer giving the depth of the current node
Definition at line 23 of file TreeGrow.c.
References C_Node(), C_splitnode(), C_splitsurrogate(), C_surrogates(), C_TreeGrow(), check_depth(), get_maxsurrogate(), get_nobs(), get_splitctrl(), get_stump(), get_tgctrl(), S3get_leftnode(), S3get_nodeterminal(), S3get_nodeweights(), S3get_rightnode(), and S3set_nodeID().
Referenced by C_TreeGrow(), R_Ensemble(), and R_TreeGrow().
SEXP R_TreeGrow (SEXP learnsample, SEXP weights, SEXP fitmem, SEXP controls, SEXP where)
R-interface to C_TreeGrow
Parameters:
learnsample an object of class `LearningSample'
weights a vector of case weights
fitmem an object of class `TreeFitMemory'
controls an object of class `TreeControl'
where a vector of node indices for each observation
Definition at line 81 of file TreeGrow.c.
References C_init_node(), C_TreeGrow(), get_maxsurrogate(), get_ninputs(), get_nobs(), get_predict_trafo(), get_splitctrl(), ncol(), NODE_LENGTH, PL2_responsesSym, and S3get_nodeweights().