TreeGrow.h File Reference
Functions
void C_TreeGrow (SEXP node, SEXP learnsample, SEXP fitmem, SEXP controls, int *where, int *nodenum, int depth)
Function Documentation
void C_TreeGrow (SEXP node, SEXP learnsample, SEXP fitmem, SEXP controls, int * where, int * nodenum, int depth)
The main tree growing function, handles the recursion.
Parameters:
node a list representing the current node
learnsample an object of class `LearningSample'
fitmem an object of class `TreeFitMemory'
controls an object of class `TreeControl'
where a pointer to an integer vector of n-elements
nodenum a pointer to a integer vector of length 1
depth an integer giving the depth of the current node
Definition at line 23 of file TreeGrow.c.
References C_Node(), C_splitnode(), C_splitsurrogate(), C_surrogates(), C_TreeGrow(), check_depth(), get_maxsurrogate(), get_nobs(), get_splitctrl(), get_stump(), get_tgctrl(), S3get_leftnode(), S3get_nodeterminal(), S3get_nodeweights(), S3get_rightnode(), and S3set_nodeID().
Referenced by C_TreeGrow(), R_Ensemble(), and R_TreeGrow().