Utils.c File Reference
#include `party.h`
Functions
void C_kronecker (const double *A, const int m, const int n, const double *B, const int r, const int s, double *ans)
SEXP R_kronecker (SEXP A, SEXP B)
void CR_La_svd (SEXP jobu, SEXP jobv, SEXP x, SEXP s, SEXP u, SEXP v, SEXP method)
SEXP CR_svd (SEXP x, SEXP svdmem)
void C_MPinv (SEXP x, double tol, SEXP svdmem, SEXP ans)
SEXP R_MPinv (SEXP x, SEXP tol, SEXP svdmem)
double C_max (const double *x, const int n)
SEXP R_max (SEXP x)
void C_abs (double *x, int n)
SEXP R_abs (SEXP x)
void C_matprod (double *x, int nrx, int ncx, double *y, int nry, int ncy, double *z)
SEXP R_matprod (SEXP x, SEXP y)
void C_matprodT (double *x, int nrx, int ncx, double *y, int nry, int ncy, double *z)
SEXP R_matprodT (SEXP x, SEXP y)
void C_SampleNoReplace (int *x, int m, int k, int *ans)
SEXP R_permute (SEXP m)
SEXP R_rsubset (SEXP m, SEXP k)
void C_ProbSampleNoReplace (int n, double *p, int *perm, int nans, int *ans)
int i_in_set (int i, int *iset, int p)
int C_i_in_set (int i, SEXP set)
int nrow (SEXP x)
int ncol (SEXP x)
int C_whichmax (double *pvalue, double *teststat, int ninputs)
SEXP R_whichmax (SEXP x, SEXP y)
SEXP R_listplus (SEXP a, SEXP b, SEXP which)
SEXP R_modify_response (SEXP x, SEXP vf)
double F77_SUB() unifrnd (void)
void C_SampleSplitting (int n, double *prob, int *weights, int k)
void C_remove_weights (SEXP subtree)
SEXP R_remove_weights (SEXP subtree)
double * C_tempweights (int j, SEXP weights, SEXP fitmem, SEXP inputs)
Detailed Description
Some commonly needed utility functions.
Author:
Author hothorn
Date:
Date 2009-01-29 10:48:11 +0100 (Thu, 29 Jan 2009)
Definition in file Utils.c.
Function Documentation
void C_abs (double * x, int n)
absolute value
Parameters:
x numeric vector
n length(x)
Definition at line 315 of file Utils.c.
Referenced by C_absstandardize(), and R_abs().
int C_i_in_set (int i, SEXP set)
Definition at line 564 of file Utils.c.
References i_in_set().
Referenced by C_get_node().
void C_kronecker (const double * A, const int m, const int n, const double * B, const int r, const int s, double * ans)
Computes the Kronecker product of two matrices
Parameters:
A matrix
m nrow(A)
n ncol(A)
B matrix
r nrow(B)
s ncol(B)
ans return value; a pointer to a REALSXP-vector of length (mr x ns)
Definition at line 23 of file Utils.c.
Referenced by C_ExpectCovarLinearStatistic(), and R_kronecker().
void C_matprod (double * x, int nrx, int ncx, double * y, int nry, int ncy, double * z)
matrix product x *% y
Parameters:
x a matrix
nrx number of rows of x
ncx number of cols of x
y a matrix
nry number of rows of y
ncy number of cols of y
z a matrix of dimension nrx x ncy
Definition at line 353 of file Utils.c.
Referenced by R_matprod().
void C_matprodT (double * x, int nrx, int ncx, double * y, int nry, int ncy, double * z)
matrix product x *% t(y)
Parameters:
x a matrix
nrx number of rows of x
ncx number of cols of x
y a matrix
nry number of rows of y
ncy number of cols of y
z a matrix of dimension nrx x ncy
Definition at line 405 of file Utils.c.
Referenced by R_matprodT().
double C_max (const double * x, const int n)
the maximum of a double vector
Parameters:
x vector
n its length
Definition at line 278 of file Utils.c.
Referenced by C_maxabsTestStatistic(), C_MonteCarlo(), C_Node(), and R_max().
void C_MPinv (SEXP x, double tol, SEXP svdmem, SEXP ans)
Moore-Penrose inverse of a matrix
Parameters:
x matrix
tol a tolerance bound
svdmem an object of class `svd_mem'
ans return value; an object of class `ExpectCovarMPinv'
Definition at line 185 of file Utils.c.
References CR_svd(), PL2_MPinvSym, PL2_rankSym, PL2_sSym, PL2_uSym, and PL2_vSym.
Referenced by C_LinStatExpCovMPinv(), and R_MPinv().
void C_ProbSampleNoReplace (int n, double * p, int * perm, int nans, int * ans)
Definition at line 508 of file Utils.c.
Referenced by C_SampleSplitting().
void C_remove_weights (SEXP subtree)
Remove weights vector from each node of a tree (in order to save memory) \*param subtree a tree
Definition at line 702 of file Utils.c.
References C_remove_weights(), S3_WEIGHTS, S3get_leftnode(), S3get_nodeterminal(), and S3get_rightnode().
Referenced by C_remove_weights(), R_Ensemble(), and R_remove_weights().
void C_SampleNoReplace (int * x, int m, int k, int * ans)
compute a permutation of a (random subset of) 0:(m-1)
Parameters:
x an integer vector of length m
m integer
k integer
ans an integer vector of length k
Definition at line 453 of file Utils.c.
Referenced by C_GlobalTest(), C_MonteCarlo(), R_permute(), and R_rsubset().
void C_SampleSplitting (int n, double * prob, int * weights, int k)
Definition at line 679 of file Utils.c.
References C_ProbSampleNoReplace().
Referenced by R_Ensemble().
double* C_tempweights (int j, SEXP weights, SEXP fitmem, SEXP inputs)
Definition at line 718 of file Utils.c.
References get_missings(), and get_weights().
Referenced by C_GlobalTest(), C_Node(), and C_surrogates().
int C_whichmax (double * pvalue, double * teststat, int ninputs)
Definition at line 583 of file Utils.c.
Referenced by C_Node(), and R_whichmax().
void CR_La_svd (SEXP jobu, SEXP jobv, SEXP x, SEXP s, SEXP u, SEXP v, SEXP method)
C- and R-interface to La_svd
Parameters:
jobu
jobv
x
s
u
v
method
Definition at line 102 of file Utils.c.
Referenced by CR_svd().
SEXP CR_svd (SEXP x, SEXP svdmem)
C- and R-interface to CR_La_svd
Parameters:
x matrix
svdmem an object of class `svd_mem'
Definition at line 153 of file Utils.c.
References CR_La_svd(), nrow(), PL2_jobuSym, PL2_jobvSym, PL2_methodSym, PL2_pSym, PL2_sSym, PL2_uSym, and PL2_vSym.
Referenced by C_MPinv().
int i_in_set (int i, int * iset, int p)
determine if i is element of the integer vector set
Parameters:
i an integer
iset a pointer to an integer vector
p length(iset)
Definition at line 549 of file Utils.c.
Referenced by C_i_in_set(), and C_splitnode().
int ncol (SEXP x)
Definition at line 575 of file Utils.c.
Referenced by C_GlobalTest(), C_IndependenceTest(), C_MonteCarlo(), C_Node(), C_splitnode(), R_Ensemble(), R_ExpectCovarInfluence(), R_ExpectCovarLinearStatistic(), R_LinearStatistic(), R_matprod(), R_matprodT(), R_MPinv(), R_Node(), R_PermutedLinearStatistic(), R_split(), R_splitcategorical(), and R_TreeGrow().
int nrow (SEXP x)
Definition at line 571 of file Utils.c.
Referenced by C_GlobalTest(), C_IndependenceTest(), CR_svd(), R_ExpectCovarInfluence(), R_ExpectCovarLinearStatistic(), R_LinearStatistic(), R_matprod(), R_matprodT(), R_maxabsConditionalPvalue(), R_MPinv(), R_PermutedLinearStatistic(), R_split(), and R_splitcategorical().
SEXP R_abs (SEXP x)
R-interface to C_abs
Parameters:
x numeric vector
Definition at line 327 of file Utils.c.
References C_abs().
SEXP R_kronecker (SEXP A, SEXP B)
R-interface to C_kronecker
Parameters:
A matrix
B matrix
Definition at line 52 of file Utils.c.
References C_kronecker().
SEXP R_listplus (SEXP a, SEXP b, SEXP which)
Definition at line 618 of file Utils.c.
SEXP R_matprod (SEXP x, SEXP y)
R-interface to C_matprod
Parameters:
x a matrix
y a matrix
Definition at line 374 of file Utils.c.
References C_matprod(), ncol(), and nrow().
SEXP R_matprodT (SEXP x, SEXP y)
R-interface to C_matprodT
Parameters:
x a matrix
y a matrix
Definition at line 426 of file Utils.c.
References C_matprodT(), ncol(), and nrow().
SEXP R_max (SEXP x)
R-interface to C_max
Parameters:
x numeric vector
Definition at line 294 of file Utils.c.
References C_max().
SEXP R_modify_response (SEXP x, SEXP vf)
Definition at line 650 of file Utils.c.
References get_predict_trafo(), get_test_trafo(), get_transformation(), and get_variable().
SEXP R_MPinv (SEXP x, SEXP tol, SEXP svdmem)
R-interface to C_MPinv
Parameters:
x matrix
tol a tolerance bound
svdmem an object of class `svd_mem'
Definition at line 243 of file Utils.c.
References C_MPinv(), ncol(), nrow(), PL2_MPinvSym, PL2_pSym, and PL2_rankSym.
SEXP R_permute (SEXP m)
R-interface to C_SampleNoReplace: the permutation case
Parameters:
m integer
Definition at line 472 of file Utils.c.
References C_SampleNoReplace().
SEXP R_remove_weights (SEXP subtree)
Definition at line 712 of file Utils.c.
References C_remove_weights().
SEXP R_rsubset (SEXP m, SEXP k)
R-interface to C_SampleNoReplace: the subset case
Parameters:
m integer
k integer
Definition at line 492 of file Utils.c.
References C_SampleNoReplace().
SEXP R_whichmax (SEXP x, SEXP y)
Definition at line 608 of file Utils.c.
References C_whichmax().
double F77_SUB() unifrnd (void)
Definition at line 677 of file Utils.c.