Utils.h File Reference
Functions
void C_kronecker (const double *A, const int m, const int n, const double *B, const int r, const int s, double *ans)
SEXP La_svd (SEXP jobu, SEXP jobv, SEXP x, SEXP s, SEXP u, SEXP v, SEXP method)
void C_SampleNoReplace (int *x, int m, int k, int *ans)
void C_MPinv (SEXP x, double tol, SEXP svdmem, SEXP ans)
double C_max (const double *x, const int n)
void C_abs (double *x, int n)
void C_matprod (double *x, int nrx, int ncx, double *y, int nry, int ncy, double *z)
void C_matprodT (double *x, int nrx, int ncx, double *y, int nry, int ncy, double *z)
int nrow (SEXP x)
int ncol (SEXP y)
int C_whichmax (double *pvalue, double *teststat, int ninputs)
int i_in_set (int i, int *iset, int p)
int C_i_in_set (int i, SEXP set)
void C_SampleSplitting (int n, double *prob, int *weights, int k)
void C_remove_weights (SEXP subtree)
double * C_tempweights (int j, SEXP weights, SEXP fitmem, SEXP inputs)
Function Documentation
void C_abs (double * x, int n)
absolute value
Parameters:
x numeric vector
n length(x)
Definition at line 315 of file Utils.c.
Referenced by C_absstandardize(), and R_abs().
int C_i_in_set (int i, SEXP set)
Definition at line 564 of file Utils.c.
References i_in_set().
Referenced by C_get_node().
void C_kronecker (const double * A, const int m, const int n, const double * B, const int r, const int s, double * ans)
Computes the Kronecker product of two matrices
Parameters:
A matrix
m nrow(A)
n ncol(A)
B matrix
r nrow(B)
s ncol(B)
ans return value; a pointer to a REALSXP-vector of length (mr x ns)
Definition at line 23 of file Utils.c.
Referenced by C_ExpectCovarLinearStatistic(), and R_kronecker().
void C_matprod (double * x, int nrx, int ncx, double * y, int nry, int ncy, double * z)
matrix product x *% y
Parameters:
x a matrix
nrx number of rows of x
ncx number of cols of x
y a matrix
nry number of rows of y
ncy number of cols of y
z a matrix of dimension nrx x ncy
Definition at line 353 of file Utils.c.
Referenced by R_matprod().
void C_matprodT (double * x, int nrx, int ncx, double * y, int nry, int ncy, double * z)
matrix product x *% t(y)
Parameters:
x a matrix
nrx number of rows of x
ncx number of cols of x
y a matrix
nry number of rows of y
ncy number of cols of y
z a matrix of dimension nrx x ncy
Definition at line 405 of file Utils.c.
Referenced by R_matprodT().
double C_max (const double * x, const int n)
the maximum of a double vector
Parameters:
x vector
n its length
Definition at line 278 of file Utils.c.
Referenced by C_maxabsTestStatistic(), C_MonteCarlo(), C_Node(), and R_max().
void C_MPinv (SEXP x, double tol, SEXP svdmem, SEXP ans)
Moore-Penrose inverse of a matrix
Parameters:
x matrix
tol a tolerance bound
svdmem an object of class `svd_mem'
ans return value; an object of class `ExpectCovarMPinv'
Definition at line 185 of file Utils.c.
References CR_svd(), PL2_MPinvSym, PL2_rankSym, PL2_sSym, PL2_uSym, and PL2_vSym.
Referenced by C_LinStatExpCovMPinv(), and R_MPinv().
void C_remove_weights (SEXP subtree)
Remove weights vector from each node of a tree (in order to save memory) \*param subtree a tree
Definition at line 702 of file Utils.c.
References C_remove_weights(), S3_WEIGHTS, S3get_leftnode(), S3get_nodeterminal(), and S3get_rightnode().
Referenced by C_remove_weights(), R_Ensemble(), and R_remove_weights().
void C_SampleNoReplace (int * x, int m, int k, int * ans)
compute a permutation of a (random subset of) 0:(m-1)
Parameters:
x an integer vector of length m
m integer
k integer
ans an integer vector of length k
Definition at line 453 of file Utils.c.
Referenced by C_GlobalTest(), C_MonteCarlo(), R_permute(), and R_rsubset().
void C_SampleSplitting (int n, double * prob, int * weights, int k)
Definition at line 679 of file Utils.c.
References C_ProbSampleNoReplace().
Referenced by R_Ensemble().
double* C_tempweights (int j, SEXP weights, SEXP fitmem, SEXP inputs)
Definition at line 718 of file Utils.c.
References get_missings(), and get_weights().
Referenced by C_GlobalTest(), C_Node(), and C_surrogates().
int C_whichmax (double * pvalue, double * teststat, int ninputs)
Definition at line 583 of file Utils.c.
Referenced by C_Node(), and R_whichmax().
int i_in_set (int i, int * iset, int p)
determine if i is element of the integer vector set
Parameters:
i an integer
iset a pointer to an integer vector
p length(iset)
Definition at line 549 of file Utils.c.
Referenced by C_i_in_set(), and C_splitnode().
SEXP La_svd (SEXP jobu, SEXP jobv, SEXP x, SEXP s, SEXP u, SEXP v, SEXP method)
int ncol (SEXP y)
Definition at line 575 of file Utils.c.
Referenced by C_GlobalTest(), C_IndependenceTest(), C_MonteCarlo(), C_Node(), C_splitnode(), R_Ensemble(), R_ExpectCovarInfluence(), R_ExpectCovarLinearStatistic(), R_LinearStatistic(), R_matprod(), R_matprodT(), R_MPinv(), R_Node(), R_PermutedLinearStatistic(), R_split(), R_splitcategorical(), and R_TreeGrow().
int nrow (SEXP x)
Definition at line 571 of file Utils.c.
Referenced by C_GlobalTest(), C_IndependenceTest(), CR_svd(), R_ExpectCovarInfluence(), R_ExpectCovarLinearStatistic(), R_LinearStatistic(), R_matprod(), R_matprodT(), R_maxabsConditionalPvalue(), R_MPinv(), R_PermutedLinearStatistic(), R_split(), and R_splitcategorical().