foldersTree = gFld("<b>party</b>", "", "")
     insDoc(foldersTree, gLnk("Main Page", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("cexpcov.c", "", "cexpcov_8c.html"))
       insDoc(aux1, gLnk("CIstuff.c", "", "CIstuff_8c.html"))
       insDoc(aux1, gLnk("Classes.c", "", "Classes_8c.html"))
       insDoc(aux1, gLnk("Classes.h", "", "Classes_8h.html"))
       insDoc(aux1, gLnk("Convenience.c", "", "Convenience_8c.html"))
       insDoc(aux1, gLnk("Convenience.h", "", "Convenience_8h.html"))
       insDoc(aux1, gLnk("Distributions.c", "", "Distributions_8c.html"))
       insDoc(aux1, gLnk("Distributions.h", "", "Distributions_8h.html"))
       insDoc(aux1, gLnk("dummyvar.c", "", "dummyvar_8c.html"))
       insDoc(aux1, gLnk("IndependenceTest.c", "", "IndependenceTest_8c.html"))
       insDoc(aux1, gLnk("IndependenceTest.h", "", "IndependenceTest_8h.html"))
       insDoc(aux1, gLnk("LinearStatistic.c", "", "LinearStatistic_8c.html"))
       insDoc(aux1, gLnk("LinearStatistic.h", "", "LinearStatistic_8h.html"))
       insDoc(aux1, gLnk("mvt.h", "", "mvt_8h.html"))
       insDoc(aux1, gLnk("Node.c", "", "Node_8c.html"))
       insDoc(aux1, gLnk("Node.h", "", "Node_8h.html"))
       insDoc(aux1, gLnk("party.h", "", "party_8h.html"))
       insDoc(aux1, gLnk("partycommon.c", "", "partycommon_8c.html"))
       insDoc(aux1, gLnk("PL2_common.h", "", "PL2__common_8h.html"))
       insDoc(aux1, gLnk("Predict.c", "", "Predict_8c.html"))
       insDoc(aux1, gLnk("Predict.h", "", "Predict_8h.html"))
       insDoc(aux1, gLnk("randomF77.c", "", "randomF77_8c.html"))
       insDoc(aux1, gLnk("S3Classes.c", "", "S3Classes_8c.html"))
       insDoc(aux1, gLnk("S3Classes.h", "", "S3Classes_8h.html"))
       insDoc(aux1, gLnk("Splits.c", "", "Splits_8c.html"))
       insDoc(aux1, gLnk("Splits.h", "", "Splits_8h.html"))
       insDoc(aux1, gLnk("TestStatistic.c", "", "TestStatistic_8c.html"))
       insDoc(aux1, gLnk("TestStatistic.h", "", "TestStatistic_8h.html"))
       insDoc(aux1, gLnk("TreeGrow.c", "", "TreeGrow_8c.html"))
       insDoc(aux1, gLnk("Utils.c", "", "Utils_8c.html"))
       insDoc(aux1, gLnk("Utils.h", "", "Utils_8h.html"))
     insDoc(foldersTree, gLnk("File Members", "", "globals.html"))
aux1 = insFld(foldersTree, gFld("Related Pages", "", "pages.html"))
       insDoc(aux1, gLnk("Todo List", "", "todo.html"))
