.TH "src/ Directory Reference" 3 "16 Feb 2006" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/ Directory Reference \- 
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBClasses.c\fP"
.br
.ti -1c
.RI "file \fBClasses.h\fP"
.br
.ti -1c
.RI "file \fBConvenience.c\fP"
.br
.ti -1c
.RI "file \fBConvenience.h\fP"
.br
.ti -1c
.RI "file \fBDistributions.c\fP"
.br
.ti -1c
.RI "file \fBDistributions.h\fP"
.br
.ti -1c
.RI "file \fBIndependenceTest.c\fP"
.br
.ti -1c
.RI "file \fBIndependenceTest.h\fP"
.br
.ti -1c
.RI "file \fBLinearStatistic.c\fP"
.br
.ti -1c
.RI "file \fBLinearStatistic.h\fP"
.br
.ti -1c
.RI "file \fBmvt.h\fP"
.br
.ti -1c
.RI "file \fBNode.c\fP"
.br
.ti -1c
.RI "file \fBNode.h\fP"
.br
.ti -1c
.RI "file \fBparty.h\fP"
.br
.ti -1c
.RI "file \fBPredict.c\fP"
.br
.ti -1c
.RI "file \fBPredict.h\fP"
.br
.ti -1c
.RI "file \fBrandomF77.c\fP"
.br
.ti -1c
.RI "file \fBRandomForest.c\fP"
.br
.ti -1c
.RI "file \fBS3Classes.c\fP"
.br
.ti -1c
.RI "file \fBS3Classes.h\fP"
.br
.ti -1c
.RI "file \fBSplits.c\fP"
.br
.ti -1c
.RI "file \fBSplits.h\fP"
.br
.ti -1c
.RI "file \fBSurrogateSplits.c\fP"
.br
.ti -1c
.RI "file \fBSurrogateSplits.h\fP"
.br
.ti -1c
.RI "file \fBTestStatistic.c\fP"
.br
.ti -1c
.RI "file \fBTestStatistic.h\fP"
.br
.ti -1c
.RI "file \fBTreeGrow.c\fP"
.br
.ti -1c
.RI "file \fBTreeGrow.h\fP"
.br
.ti -1c
.RI "file \fBUtils.c\fP"
.br
.ti -1c
.RI "file \fBUtils.h\fP"
.br
.in -1c
