.TH "cexpcov.c" 3 "14 Apr 2005" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cexpcov.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <R.h>\fP
.br
\fC#include <Rmath.h>\fP
.br
\fC#include <Rinternals.h>\fP
.br
\fC#include 'party.h'\fP
.br
.SS "Functions"

.in +1c
.ti -1c
.RI "SEXP \fBkronecker\fP (SEXP A, SEXP B)"
.br
.ti -1c
.RI "void \fBsetAllZero\fP (SEXP A)"
.br
.ti -1c
.RI "SEXP \fBec\fP (SEXP Weights, SEXP Scores, SEXP cweights)"
.br
.ti -1c
.RI "SEXP \fBevS\fP (SEXP Scores, SEXP cweights)"
.br
.ti -1c
.RI "SEXP \fBevL\fP (SEXP Weights, SEXP Scores, SEXP cweights, SEXP evSans)"
.br
.ti -1c
.RI "SEXP \fBev\fP (SEXP Weights, SEXP Scores, SEXP cweights)"
.br
.in -1c
.SH "FUNCTION DOCUMENTATION"
.PP 
.SS "SEXP ec (SEXP Weights, SEXP Scores, SEXP cweights)"
.PP
Definition at line 81 of file cexpcov.c.
.PP
References aindx(), error, kronecker(), and setAllZero().
.SS "SEXP ev (SEXP Weights, SEXP Scores, SEXP cweights)"
.PP
Definition at line 455 of file cexpcov.c.
.PP
References evL(), and evS().
.SS "SEXP evL (SEXP Weights, SEXP Scores, SEXP cweights, SEXP evSans)"
.PP
Definition at line 348 of file cexpcov.c.
.PP
References aindx(), error, and setAllZero().
.PP
Referenced by ev().
.SS "SEXP evS (SEXP Scores, SEXP cweights)"
.PP
Definition at line 266 of file cexpcov.c.
.PP
References aindx(), error, and setAllZero().
.PP
Referenced by ev().
.SS "SEXP kronecker (SEXP A, SEXP B)"
.PP
Definition at line 7 of file cexpcov.c.
.PP
References aindx(), and error.
.PP
Referenced by ec().
.SS "void setAllZero (SEXP A)"
.PP
Definition at line 68 of file cexpcov.c.
.PP
Referenced by ec(), evL(), and evS().
.SH "AUTHOR"
.PP 
Generated automatically by Doxygen for party from the source code.
