.TH "CIstuff.c" 3 "9 Jun 2005" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CIstuff.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'PL2_common.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "SEXP \fBR_blocksetup\fP (SEXP block)"
.br
.ti -1c
.RI "void \fBC_blockperm\fP (SEXP blocksetup, int *ans)"
.br
.ti -1c
.RI "SEXP \fBR_blockperm\fP (SEXP block)"
.br
.ti -1c
.RI "SEXP \fBR_MonteCarloIndependenceTest\fP (SEXP x, SEXP y, SEXP block, SEXP B)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Some additional functionality for package `ConditionalInference'
.PP
\fBAuthor:\fP
.RS 4
\fBAuthor\fP.RS 4
hothorn 
.RE
.PP
.RE
.PP
\fBDate:\fP
.RS 4
\fBDate\fP.RS 4
2005/06/09 12:21:38 
.RE
.PP
.RE
.PP

.PP
Definition in file \fBCIstuff.c\fP.
.SH "Function Documentation"
.PP 
.SS "void C_blockperm (SEXP blocksetup, int * ans)"
.PP
Block permutation 
.PP
\fBParameters:\fP
.RS 4
\fIblocksetup\fP an object as returned by function `R_blocksetup' 
.br
\fIans\fP return value, the (block)-permutation of 1:n 
.RE
.PP

.PP
Definition at line 66 of file CIstuff.c.
.PP
References C_SampleNoReplace().
.PP
Referenced by R_blockperm(), and R_MonteCarloIndependenceTest().
.SS "SEXP R_blockperm (SEXP block)"
.PP
Definition at line 95 of file CIstuff.c.
.PP
References C_blockperm(), and R_blocksetup().
.SS "SEXP R_blocksetup (SEXP block)"
.PP
Definition at line 12 of file CIstuff.c.
.PP
Referenced by R_blockperm(), and R_MonteCarloIndependenceTest().
.SS "SEXP R_MonteCarloIndependenceTest (SEXP x, SEXP y, SEXP block, SEXP B)"
.PP
Definition at line 108 of file CIstuff.c.
.PP
References C_blockperm(), C_PermutedLinearStatistic(), ncol(), nrow(), and R_blocksetup().
.SH "Author"
.PP 
Generated automatically by Doxygen for party from the source code.
