.TH "Distributions.c" 3 "26 Jun 2008" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Distributions.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'party.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBC_quadformConditionalPvalue\fP (const double tstat, const double df)"
.br
.ti -1c
.RI "SEXP \fBR_quadformConditionalPvalue\fP (SEXP tstat, SEXP df)"
.br
.ti -1c
.RI "double \fBC_maxabsConditionalPvalue\fP (const double tstat, const double *Sigma, const int pq, int *maxpts, double *releps, double *abseps, double *tol)"
.br
.ti -1c
.RI "SEXP \fBR_maxabsConditionalPvalue\fP (SEXP tstat, SEXP Sigma, SEXP maxpts, SEXP releps, SEXP abseps, SEXP tol)"
.br
.ti -1c
.RI "void \fBC_MonteCarlo\fP (double *criterion, SEXP learnsample, SEXP weights, SEXP fitmem, SEXP varctrl, SEXP gtctrl, double *ans_pvalues)"
.br
.ti -1c
.RI "SEXP \fBR_MonteCarlo\fP (SEXP criterion, SEXP learnsample, SEXP weights, SEXP fitmem, SEXP varctrl, SEXP gtctrl)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Conditional Distributions
.PP
\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
hothorn 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2007-07-12 18:49:01 +0200 (Thu, 12 Jul 2007) 
.RE
.PP

.PP
Definition in file \fBDistributions.c\fP.
.SH "Function Documentation"
.PP 
.SS "double C_maxabsConditionalPvalue (const double tstat, const double * Sigma, const int pq, int * maxpts, double * releps, double * abseps, double * tol)"
.PP
Conditional asymptotic P-value of a maxabs-type test statistic
.br
 Basically the functionality from package `mvtnorm' 
.br
 
.PP
\fBParameters:\fP
.RS 4
\fItstat\fP test statitstic 
.br
\fISigma\fP covariance matrix 
.br
\fIpq\fP nrow(Sigma) 
.br
\fImaxpts\fP number of Monte-Carlo steps 
.br
\fIreleps\fP relative error 
.br
\fIabseps\fP absolute error 
.br
\fItol\fP tolerance 
.RE
.PP

.PP
Definition at line 52 of file Distributions.c.
.PP
References mvtdst().
.PP
Referenced by C_ConditionalPvalue(), and R_maxabsConditionalPvalue().
.SS "void C_MonteCarlo (double * criterion, SEXP learnsample, SEXP weights, SEXP fitmem, SEXP varctrl, SEXP gtctrl, double * ans_pvalues)"
.PP
Monte-Carlo approximation to the conditional pvalues 
.PP
\fBParameters:\fP
.RS 4
\fIcriterion\fP vector of node criteria for each input 
.br
\fIlearnsample\fP an object of class `LearningSample' 
.br
\fIweights\fP case weights 
.br
\fIfitmem\fP an object of class `TreeFitMemory' 
.br
\fIvarctrl\fP an object of class `VariableControl' 
.br
\fIgtctrl\fP an object of class `GlobalTestControl' 
.br
\fIans_pvalues\fP return values; vector of adjusted pvalues 
.RE
.PP

.PP
Definition at line 169 of file Distributions.c.
.PP
References C_LinearStatistic(), C_max(), C_PermutedLinearStatistic(), C_SampleNoReplace(), C_TeststatCriterion(), get_ninputs(), get_nobs(), get_nresample(), get_test_trafo(), get_transformation(), get_varmemory(), has_missings(), ncol(), PL2_expcovinfSym, PL2_inputsSym, PL2_linearstatisticSym, PL2_responsesSym, and PL2_sumweightsSym.
.PP
Referenced by C_GlobalTest(), and R_MonteCarlo().
.SS "double C_quadformConditionalPvalue (const double tstat, const double df)"
.PP
Conditional asymptotic P-value of a quadratic form
.br
 
.PP
\fBParameters:\fP
.RS 4
\fItstat\fP test statistic 
.br
\fIdf\fP degree of freedom 
.RE
.PP

.PP
Definition at line 18 of file Distributions.c.
.PP
Referenced by C_ConditionalPvalue(), and R_quadformConditionalPvalue().
.SS "SEXP R_maxabsConditionalPvalue (SEXP tstat, SEXP Sigma, SEXP maxpts, SEXP releps, SEXP abseps, SEXP tol)"
.PP
R-interface to C_maxabsConditionalPvalue 
.br
 
.PP
\fBParameters:\fP
.RS 4
\fItstat\fP test statitstic 
.br
\fISigma\fP covariance matrix 
.br
\fImaxpts\fP number of Monte-Carlo steps 
.br
\fIreleps\fP relative error 
.br
\fIabseps\fP absolute error 
.br
\fItol\fP tolerance 
.RE
.PP

.PP
Definition at line 142 of file Distributions.c.
.PP
References C_maxabsConditionalPvalue(), and nrow().
.SS "SEXP R_MonteCarlo (SEXP criterion, SEXP learnsample, SEXP weights, SEXP fitmem, SEXP varctrl, SEXP gtctrl)"
.PP
R-interface to C_MonteCarlo 
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIcriterion\fP vector of node criteria for each input 
.br
\fIlearnsample\fP an object of class `LearningSample' 
.br
\fIweights\fP case weights 
.br
\fIfitmem\fP an object of class `TreeFitMemory' 
.br
\fIvarctrl\fP an object of class `VariableControl' 
.br
\fIgtctrl\fP an object of class `GlobalTestControl' 
.RE
.PP

.PP
Definition at line 278 of file Distributions.c.
.PP
References C_MonteCarlo(), and get_ninputs().
.SS "SEXP R_quadformConditionalPvalue (SEXP tstat, SEXP df)"
.PP
R-interface to C_quadformConditionalPvalue
.br
 
.PP
\fBParameters:\fP
.RS 4
\fItstat\fP test statitstic 
.br
\fIdf\fP degree of freedom 
.RE
.PP

.PP
Definition at line 29 of file Distributions.c.
.PP
References C_quadformConditionalPvalue().
.SH "Author"
.PP 
Generated automatically by Doxygen for party from the source code.
