.TH "dummyvar.c" 3 "9 Jun 2005" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dummyvar.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <R.h>\fP
.br
\fC#include <Rmath.h>\fP
.br
\fC#include <Rdefines.h>\fP
.br
\fC#include <Rinternals.h>\fP
.br
\fC#include 'party.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "SEXP \fBdummyvar\fP (SEXP x, SEXP transposed)"
.br
.ti -1c
.RI "SEXP \fBcontcat\fP (SEXP x, SEXP cutpoints)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "SEXP contcat (SEXP x, SEXP cutpoints)"
.PP
Definition at line 59 of file dummyvar.c.
.PP
References aindx().
.SS "SEXP dummyvar (SEXP x, SEXP transposed)"
.PP
Definition at line 8 of file dummyvar.c.
.PP
References aindx().
.SH "Author"
.PP 
Generated automatically by Doxygen for party from the source code.
