.TH "LinearStatistic.c" 3 "25 Aug 2006" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinearStatistic.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'party.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBC_LinearStatistic\fP (const double *x, const int p, const double *y, const int q, const double *weights, const int n, double *ans)"
.br
.ti -1c
.RI "SEXP \fBR_LinearStatistic\fP (SEXP x, SEXP y, SEXP weights)"
.br
.ti -1c
.RI "void \fBC_ExpectCovarInfluence\fP (const double *y, const int q, const double *weights, const int n, SEXP ans)"
.br
.ti -1c
.RI "SEXP \fBR_ExpectCovarInfluence\fP (SEXP y, SEXP weights)"
.br
.ti -1c
.RI "void \fBC_ExpectCovarLinearStatistic\fP (const double *x, const int p, const double *y, const int q, const double *weights, const int n, const SEXP expcovinf, SEXP ans)"
.br
.ti -1c
.RI "SEXP \fBR_ExpectCovarLinearStatistic\fP (SEXP x, SEXP y, SEXP weights, SEXP expcovinf)"
.br
.ti -1c
.RI "void \fBC_PermutedLinearStatistic\fP (const double *x, const int p, const double *y, const int q, const int n, const int nperm, const int *indx, const int *perm, double *ans)"
.br
.ti -1c
.RI "SEXP \fBR_PermutedLinearStatistic\fP (SEXP x, SEXP y, SEXP indx, SEXP perm)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Linear statistics for conditional inference based on Strasser & Weber (1999)
.PP
\fBAuthor:\fP
.RS 4
\fBAuthor\fP.RS 4
hothorn 
.RE
.PP
.RE
.PP
\fBDate:\fP
.RS 4
\fBDate\fP.RS 4
2006-08-25 10:53:10 +0200 (Fri, 25 Aug 2006) 
.RE
.PP
.RE
.PP

.PP
Definition in file \fBLinearStatistic.c\fP.
.SH "Function Documentation"
.PP 
.SS "void C_ExpectCovarInfluence (const double * y, const int q, const double * weights, const int n, SEXP ans)"
.PP
Conditional expectation and covariance of the influence function
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP values of the influence function 
.br
\fIq\fP dimension of the influence function 
.br
\fIweights\fP case weights 
.br
\fIn\fP number of observations 
.br
\fIans\fP return value; an object of class `ExpectCovarInfluence'
.RE
.PP

.PP
Definition at line 101 of file LinearStatistic.c.
.PP
References PL2_covarianceSym, PL2_expectationSym, and PL2_sumweightsSym.
.PP
Referenced by C_GlobalTest(), C_LinStatExpCov(), C_surrogates(), and R_ExpectCovarInfluence().
.SS "void C_ExpectCovarLinearStatistic (const double * x, const int p, const double * y, const int q, const double * weights, const int n, const SEXP expcovinf, SEXP ans)"
.PP
Conditional expectation and covariance of the a linear statistic
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP values of the transformation 
.br
\fIp\fP dimension of the transformation 
.br
\fIy\fP values of the influence function 
.br
\fIq\fP dimension of the influence function 
.br
\fIweights\fP case weights 
.br
\fIn\fP number of observations 
.br
\fIexpcovinf\fP an object of class `ExpectCovarInfluence' 
.br
\fIans\fP return value; an object of class `ExpectCovar'
.RE
.PP

.PP
Definition at line 213 of file LinearStatistic.c.
.PP
References C_kronecker(), PL2_covarianceSym, PL2_expectationSym, and PL2_sumweightsSym.
.PP
Referenced by C_LinStatExpCov(), and R_ExpectCovarLinearStatistic().
.SS "void C_LinearStatistic (const double * x, const int p, const double * y, const int q, const double * weights, const int n, double * ans)"
.PP
Computes the linear statistic, formula (1) in the paper
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP values of the transformation 
.br
\fIp\fP dimension of the transformation 
.br
\fIy\fP values of the influence function 
.br
\fIq\fP dimension of the influence function 
.br
\fIweights\fP case weights 
.br
\fIn\fP number of observations 
.br
\fIans\fP return value; a pointer to a REALSXP-vector of length pq
.RE
.PP

.PP
Definition at line 23 of file LinearStatistic.c.
.PP
Referenced by C_LinStatExpCov(), C_MonteCarlo(), and R_LinearStatistic().
.SS "void C_PermutedLinearStatistic (const double * x, const int p, const double * y, const int q, const int n, const int nperm, const int * indx, const int * perm, double * ans)"
.PP
Linear Statistic with permuted indices
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP values of the transformation 
.br
\fIp\fP dimension of the transformation 
.br
\fIy\fP values of the influence function 
.br
\fIq\fP dimension of the influence function 
.br
\fIn\fP number of observations 
.br
\fInperm\fP number of permutations 
.br
\fIindx\fP indices for the x-part 
.br
\fIperm\fP (permuted) indices for the y-part 
.br
\fIans\fP return value; a pointer to a REALSXP-vector of length pq
.RE
.PP

.PP
Definition at line 351 of file LinearStatistic.c.
.PP
Referenced by C_MonteCarlo(), and R_PermutedLinearStatistic().
.SS "SEXP R_ExpectCovarInfluence (SEXP y, SEXP weights)"
.PP
R-interface to C_ExpectCovarInfluence
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP values of the influence function 
.br
\fIweights\fP case weights
.RE
.PP

.PP
Definition at line 171 of file LinearStatistic.c.
.PP
References C_ExpectCovarInfluence(), ncol(), nrow(), PL2_covarianceSym, PL2_expectationSym, and PL2_sumweightsSym.
.SS "SEXP R_ExpectCovarLinearStatistic (SEXP x, SEXP y, SEXP weights, SEXP expcovinf)"
.PP
R-interface to C_ExpectCovarLinearStatistic
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP values of the transformation 
.br
\fIy\fP values of the influence function 
.br
\fIweights\fP case weights 
.br
\fIexpcovinf\fP an object of class `ExpectCovarInfluence'
.RE
.PP

.PP
Definition at line 306 of file LinearStatistic.c.
.PP
References C_ExpectCovarLinearStatistic(), ncol(), nrow(), PL2_covarianceSym, and PL2_expectationSym.
.SS "SEXP R_LinearStatistic (SEXP x, SEXP y, SEXP weights)"
.PP
R-interface to C_LinearStatistic 
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP values of the transformation 
.br
\fIy\fP values of the influence function 
.br
\fIweights\fP case weights
.RE
.PP

.PP
Definition at line 59 of file LinearStatistic.c.
.PP
References C_LinearStatistic(), ncol(), and nrow().
.SS "SEXP R_PermutedLinearStatistic (SEXP x, SEXP y, SEXP indx, SEXP perm)"
.PP
Linear Statistic with permuted indices
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP values of the transformation 
.br
\fIy\fP values of the influence function 
.br
\fIindx\fP indices for the x-part 
.br
\fIperm\fP (permuted) indices for the y-part
.RE
.PP

.PP
Definition at line 384 of file LinearStatistic.c.
.PP
References C_PermutedLinearStatistic(), ncol(), and nrow().
.SH "Author"
.PP 
Generated automatically by Doxygen for party from the source code.
