.TH "mvt.h" 3 "25 Aug 2006" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mvt.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "void F77_NAME( \fBmvtdst\fP )(int *n, int *nu, double *lower, double *upper, int *infin, double *corr, double *delta, int *maxpts, double *abseps, double *releps, double *tol, double *error, double *value, int *inform)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "void F77_NAME( \fBmvtdst\fP)(int *n, int *nu, double *lower, double *upper, int *infin, double *corr, double *delta, int *maxpts, double *abseps, double *releps, double *tol, double *error, double *value, int *inform)"
.PP
Definition at line 2 of file mvt.h.
.PP
Referenced by C_maxabsConditionalPvalue().
.SH "Author"
.PP 
Generated automatically by Doxygen for party from the source code.
