.TH "mvt.h" 3 "28 Oct 2008" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mvt.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void F77_NAME() \fBmvtdst\fP (int *n, int *nu, double *lower, double *upper, int *infin, double *corr, double *delta, int *maxpts, double *abseps, double *releps, double *error, double *value, int *inform)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void F77_NAME() mvtdst (int * n, int * nu, double * lower, double * upper, int * infin, double * corr, double * delta, int * maxpts, double * abseps, double * releps, double * error, double * value, int * inform)"
.PP
Referenced by C_maxabsConditionalPvalue().
.SH "Author"
.PP 
Generated automatically by Doxygen for party from the source code.
