.TH "Node.c" 3 "28 Oct 2008" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'party.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBC_prediction\fP (const double *y, int n, int q, const double *weights, const double sweights, double *ans)"
.br
.ti -1c
.RI "void \fBC_Node\fP (SEXP node, SEXP learnsample, SEXP weights, SEXP fitmem, SEXP controls, int TERMINAL)"
.br
.ti -1c
.RI "SEXP \fBR_Node\fP (SEXP learnsample, SEXP weights, SEXP fitmem, SEXP controls)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Node computations
.PP
\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
hothorn 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2007-09-26 14:44:59 +0200 (Wed, 26 Sep 2007) 
.RE
.PP

.PP
Definition in file \fBNode.c\fP.
.SH "Function Documentation"
.PP 
.SS "void C_Node (SEXP node, SEXP learnsample, SEXP weights, SEXP fitmem, SEXP controls, int TERMINAL)"
.PP
The main function for all node computations 
.PP
\fBParameters:\fP
.RS 4
\fInode\fP an initialized node (an S3 object!) 
.br
\fIlearnsample\fP an object of class `LearningSample' 
.br
\fIweights\fP case weights 
.br
\fIfitmem\fP an object of class `TreeFitMemory' 
.br
\fIcontrols\fP an object of class `TreeControl' 
.br
\fITERMINAL\fP logical indicating if this node will be a terminal node 
.RE
.PP

.PP
Definition at line 48 of file Node.c.
.PP
References C_GlobalTest(), C_init_nominalsplit(), C_init_orderedsplit(), C_max(), C_prediction(), C_split(), C_splitcategorical(), C_standardize(), C_tempweights(), C_whichmax(), get_dimension(), get_gtctrl(), get_levels(), get_mincriterion(), get_minsplit(), get_ninputs(), get_nobs(), get_ordering(), get_predict_trafo(), get_savesplitstats(), get_splitctrl(), get_splitstatistics(), get_test_trafo(), get_tgctrl(), get_tol(), get_transformation(), get_varctrl(), get_variable(), get_varmemory(), has_missings(), is_nominal(), ncol(), PL2_covarianceSym, PL2_expcovinfSym, PL2_expectationSym, PL2_inputsSym, PL2_linearstatisticSym, PL2_linexpcov2sampleSym, PL2_responsesSym, PL2_sumweightsSym, S3_SUMWEIGHTS, S3get_criterion(), S3get_maxcriterion(), S3get_prediction(), S3get_primarysplit(), S3get_splitpoint(), S3get_splitstatistics(), S3get_table(), S3get_teststat(), S3set_nodeterminal(), and S3set_variableID().
.PP
Referenced by C_TreeGrow(), and R_Node().
.SS "void C_prediction (const double * y, int n, int q, const double * weights, const double sweights, double * ans)"
.PP
Compute prediction of a node 
.PP
\fBParameters:\fP
.RS 4
\fIy\fP the response variable (raw numeric values or dummy encoded factor) 
.br
\fIn\fP number of observations 
.br
\fIq\fP number of columns of y 
.br
\fIweights\fP case weights 
.br
\fIsweights\fP sum of case weights 
.br
\fIans\fP return value; the q-dimensional predictions 
.RE
.PP

.PP
Definition at line 22 of file Node.c.
.PP
Referenced by C_Node().
.SS "SEXP R_Node (SEXP learnsample, SEXP weights, SEXP fitmem, SEXP controls)"
.PP
R-interface to C_Node 
.PP
\fBParameters:\fP
.RS 4
\fIlearnsample\fP an object of class `LearningSample' 
.br
\fIweights\fP case weights 
.br
\fIfitmem\fP an object of class `TreeFitMemory' 
.br
\fIcontrols\fP an object of class `TreeControl' 
.RE
.PP

.PP
Definition at line 227 of file Node.c.
.PP
References C_init_node(), C_Node(), get_maxsurrogate(), get_ninputs(), get_nobs(), get_predict_trafo(), get_splitctrl(), ncol(), NODE_LENGTH, and PL2_responsesSym.
.SH "Author"
.PP 
Generated automatically by Doxygen for party from the source code.
