.TH "Node.h" 3 "30 Jan 2008" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Node.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBC_Node\fP (SEXP node, SEXP learnsample, SEXP weights, SEXP fitmem, SEXP controls, int TERMINAL)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void C_Node (SEXP node, SEXP learnsample, SEXP weights, SEXP fitmem, SEXP controls, int TERMINAL)"
.PP
The main function for all node computations 
.PP
\fBParameters:\fP
.RS 4
\fInode\fP an initialized node (an S3 object!) 
.br
\fIlearnsample\fP an object of class `LearningSample' 
.br
\fIweights\fP case weights 
.br
\fIfitmem\fP an object of class `TreeFitMemory' 
.br
\fIcontrols\fP an object of class `TreeControl' 
.br
\fITERMINAL\fP logical indicating if this node will be a terminal node 
.RE
.PP

.PP
Definition at line 48 of file Node.c.
.PP
References C_GlobalTest(), C_init_nominalsplit(), C_init_orderedsplit(), C_max(), C_prediction(), C_split(), C_splitcategorical(), C_standardize(), C_tempweights(), C_whichmax(), get_dimension(), get_gtctrl(), get_levels(), get_mincriterion(), get_minsplit(), get_ninputs(), get_nobs(), get_ordering(), get_predict_trafo(), get_savesplitstats(), get_splitctrl(), get_splitstatistics(), get_test_trafo(), get_tgctrl(), get_tol(), get_transformation(), get_varctrl(), get_variable(), get_varmemory(), has_missings(), is_nominal(), ncol(), PL2_covarianceSym, PL2_expcovinfSym, PL2_expectationSym, PL2_inputsSym, PL2_linearstatisticSym, PL2_linexpcov2sampleSym, PL2_responsesSym, PL2_sumweightsSym, S3_SUMWEIGHTS, S3get_criterion(), S3get_maxcriterion(), S3get_prediction(), S3get_primarysplit(), S3get_splitpoint(), S3get_splitstatistics(), S3get_table(), S3get_teststat(), S3set_nodeterminal(), and S3set_variableID().
.SH "Author"
.PP 
Generated automatically by Doxygen for party from the source code.
