.TH "partycommon.c" 3 "9 Jun 2005" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
partycommon.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <R.h>\fP
.br
\fC#include <Rmath.h>\fP
.br
\fC#include <Rinternals.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBaindx\fP (int i, int j, int m)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int aindx (int i, int j, int m)"
.PP
Definition at line 6 of file partycommon.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for party from the source code.
