.TH "PL2_common.h" 3 "9 Jun 2005" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PL2_common.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <R.h>\fP
.br
\fC#include <Rmath.h>\fP
.br
\fC#include <Rinternals.h>\fP
.br
\fC#include <Rdefines.h>\fP
.br
\fC#include <R_ext/Applic.h>\fP
.br
\fC#include 'Classes.h'\fP
.br
\fC#include 'Utils.h'\fP
.br
\fC#include 'mvt.h'\fP
.br
\fC#include 'LinearStatistic.h'\fP
.br
\fC#include 'TestStatistic.h'\fP
.br
\fC#include 'Distributions.h'\fP
.br
\fC#include 'Convenience.h'\fP
.br
\fC#include 'S3Classes.h'\fP
.br
\fC#include 'IndependenceTest.h'\fP
.br
\fC#include 'Splits.h'\fP
.br
\fC#include 'Node.h'\fP
.br
\fC#include 'Predict.h'\fP
.br
\fC#include 'SurrogateSplits.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for party from the source code.
