.TH "Predict.h" 3 "26 Jun 2008" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Predict.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBC_splitnode\fP (SEXP node, SEXP learnsample, SEXP control)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void C_splitnode (SEXP node, SEXP learnsample, SEXP control)"
.PP
Split a node according to a splitting rule 
.br
 
.PP
\fBParameters:\fP
.RS 4
\fInode\fP the current node with primary split specified 
.br
\fIlearnsample\fP learning sample 
.br
\fIcontrol\fP an object of class `TreeControl' 
.RE
.PP
\fBTodo\fP
.RS 4
outplace the splitting since there are at least 3 functions with nearly identical code 
.RE
.PP

.PP
Definition at line 21 of file Predict.c.
.PP
References C_init_node(), get_maxsurrogate(), get_missings(), get_ninputs(), get_nobs(), get_predict_trafo(), get_splitctrl(), get_variable(), has_missings(), i_in_set(), ncol(), NODE_LENGTH, PL2_inputsSym, PL2_responsesSym, S3_LEFT, S3_RIGHT, S3get_nodeweights(), S3get_primarysplit(), S3get_splitpoint(), S3get_variableID(), and S3is_ordered().
.PP
Referenced by C_TreeGrow().
.SH "Author"
.PP 
Generated automatically by Doxygen for party from the source code.
