.TH "randomF77.c" 3 "25 Aug 2006" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
randomF77.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'party.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "void F77_SUB( \fBrndstart\fP )(void)"
.br
.ti -1c
.RI "void F77_SUB( \fBrndend\fP )(void)"
.br
.ti -1c
.RI "double F77_SUB( \fBunifrnd\fP )(void)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "void F77_SUB( \fBrndend\fP)(void)"
.PP
Definition at line 12 of file randomF77.c.
.SS "void F77_SUB( \fBrndstart\fP)(void)"
.PP
Definition at line 11 of file randomF77.c.
.SS "double F77_SUB( \fBunifrnd\fP)(void)"
.PP
Definition at line 13 of file randomF77.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for party from the source code.
