.TH "Splits.c" 3 "23 Feb 2009" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Splits.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'party.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBC_split\fP (const double *x, int p, const double *y, int q, const double *weights, int n, const int *orderx, SEXP splitctrl, SEXP linexpcov2sample, SEXP expcovinf, double *cutpoint, double *maxstat, double *statistics)"
.br
.ti -1c
.RI "SEXP \fBR_split\fP (SEXP x, SEXP y, SEXP weights, SEXP orderx, SEXP linexpcov2sample, SEXP expcovinf, SEXP splitctrl)"
.br
.ti -1c
.RI "void \fBC_splitcategorical\fP (const int *codingx, int p, const double *y, int q, const double *weights, int n, double *standstat, SEXP splitctrl, SEXP linexpcov2sample, SEXP expcovinf, double *cutpoint, int *levelset, double *maxstat, double *statistics)"
.br
.ti -1c
.RI "SEXP \fBR_splitcategorical\fP (SEXP x, SEXP codingx, SEXP y, SEXP weights, SEXP linexpcov2sample, SEXP linexpcov, SEXP expcovinf, SEXP splitctrl)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Binary splits
.PP
\fBAuthor:\fP
.RS 4
.RE
.PP
\fBAuthor\fP.RS 4
hothorn 
.RE
.PP
\fBDate:\fP
.RS 4
.RE
.PP
\fBDate\fP.RS 4
2008-10-28 18:57:51 +0100 (Tue, 28 Oct 2008) 
.RE
.PP

.PP
Definition in file \fBSplits.c\fP.
.SH "Function Documentation"
.PP 
.SS "void C_split (const double * x, int p, const double * y, int q, const double * weights, int n, const int * orderx, SEXP splitctrl, SEXP linexpcov2sample, SEXP expcovinf, double * cutpoint, double * maxstat, double * statistics)"
.PP
Search for a cutpoint in a ordered variable x maximizing a two-sample statistic w.r.t. (the influence function of ) the response variable y. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP raw numeric measurements 
.br
\fIp\fP dimension of the transformation 
.br
\fIy\fP values of the influence function 
.br
\fIq\fP dimension of the influence function 
.br
\fIweights\fP case weights 
.br
\fIn\fP number of observations 
.br
\fIorderx\fP the ordering of the transformations, i.e. R> order(x) 
.br
\fIsplitctrl\fP an object of class `SplitControl' 
.br
\fIlinexpcov2sample\fP an (uninitialized) object of class `LinStatExpectCovar' with p = 1 
.br
\fIexpcovinf\fP an initialized object of class `ExpectCovarInfluence' 
.br
\fIcutpoint\fP return value; pointer to a double for the cutpoint in x 
.br
\fImaxstat\fP return value; pointer to a double for the maximal test statistic 
.br
\fIstatistics\fP return value; pointer to a n-dim double for the statistics 
.RE
.PP

.PP
Definition at line 33 of file Splits.c.
.PP
References get_minbucket(), get_minprob(), get_tol(), PL2_covarianceSym, PL2_expectationSym, PL2_linearstatisticSym, and PL2_sumweightsSym.
.PP
Referenced by C_Node(), C_splitcategorical(), C_surrogates(), and R_split().
.SS "void C_splitcategorical (const int * codingx, int p, const double * y, int q, const double * weights, int n, double * standstat, SEXP splitctrl, SEXP linexpcov2sample, SEXP expcovinf, double * cutpoint, int * levelset, double * maxstat, double * statistics)"
.PP
Search for a cutpoint in a unordered factor x maximizing a two-sample statistic w.r.t. (the influence function of ) the response variable y. 
.PP
\fBParameters:\fP
.RS 4
\fIcodingx\fP the coding of x, i.e. as.numeric(x) 
.br
\fIp\fP dimension of the transformation 
.br
\fIy\fP values of the influence function 
.br
\fIq\fP dimension of the influence function 
.br
\fIweights\fP case weights 
.br
\fIn\fP number of observations 
.br
\fIcodingx\fP the coding of x, i.e. as.numeric(x) 
.br
\fIstandstat\fP the vector of the standardized statistics for x, y, weights 
.br
\fIsplitctrl\fP an object of class `SplitControl' 
.br
\fIlinexpcov2sample\fP an (uninitialized) object of class `LinStatExpectCovar' with p = 1 
.br
\fIexpcovinf\fP an initialized object of class `ExpectCovarInfluence' 
.br
\fIcutpoint\fP return value; pointer to a double for the cutpoint in x 
.br
\fIlevelset\fP return value; pointer to a p-dim 0/1 integer 
.br
\fImaxstat\fP return value; pointer to a double for the maximal test statistic 
.br
\fIstatistics\fP return value; pointer to a n-dim double for the statistics 
.RE
.PP

.PP
Definition at line 217 of file Splits.c.
.PP
References C_split(), and get_tol().
.PP
Referenced by C_Node(), and R_splitcategorical().
.SS "SEXP R_split (SEXP x, SEXP y, SEXP weights, SEXP orderx, SEXP linexpcov2sample, SEXP expcovinf, SEXP splitctrl)"
.PP
R-interface to C_split (does not handle ordered y's) 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP values of the transformation 
.br
\fIy\fP values of the influence function 
.br
\fIweights\fP case weights 
.br
\fIorderx\fP the ordering of the transformations, i.e. R> order(x) 
.br
\fIlinexpcov2sample\fP an (uninitialized) object of class `LinStatExpectCovar' with p = 1 
.br
\fIexpcovinf\fP an initialized object of class `ExpectCovarInfluence' 
.br
\fIsplitctrl\fP an object of class `SplitControl' 
.RE
.PP

.PP
Definition at line 175 of file Splits.c.
.PP
References C_split(), ncol(), and nrow().
.SS "SEXP R_splitcategorical (SEXP x, SEXP codingx, SEXP y, SEXP weights, SEXP linexpcov2sample, SEXP linexpcov, SEXP expcovinf, SEXP splitctrl)"
.PP
R-interface to C_splitcategorical (does not handle ordered y's) 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP the values of the x-transformation 
.br
\fIcodingx\fP the coding of x, i.e. as.numeric(x) 
.br
\fIy\fP values of the influence function 
.br
\fIweights\fP case weights 
.br
\fIlinexpcov2sample\fP an (uninitialized) object of class `LinStatExpectCovar' with p = 1 
.br
\fIlinexpcov\fP an initialized object of class `LinStatExpectCovar' 
.br
\fIexpcovinf\fP an initialized object of class `ExpectCovarInfluence' 
.br
\fIsplitctrl\fP an object of class `SplitControl' 
.RE
.PP

.PP
Definition at line 313 of file Splits.c.
.PP
References C_LinStatExpCov(), C_splitcategorical(), C_standardize(), get_dimension(), get_tol(), ncol(), nrow(), PL2_covarianceSym, PL2_expcovinfSym, PL2_expectationSym, and PL2_linearstatisticSym.
.SH "Author"
.PP 
Generated automatically by Doxygen for party from the source code.
