.TH "todo" 3 "23 Feb 2006" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List
 
.IP "\fBMember \fBC_get_node\fP(SEXP subtree, SEXP newinputs, double mincriterion, int numobs) \fP" 1c
handle surrogate splits 
.PP
.PP
 
.IP "\fBMember \fBC_splitnode\fP(SEXP node, SEXP learnsample, SEXP control) \fP" 1c
outplace the splitting since there are at least 3 functions with nearly identical code 
.PP
.PP
 
.IP "\fBMember \fBC_surrogates\fP(SEXP node, SEXP learnsample, SEXP weights, SEXP controls, SEXP fitmem) \fP" 1c
enable nominal surrogate split variables as well 
.PP

