.TH "todo" 3 "16 Jun 2009" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
 
.IP "\fBMember \fBC_get_node\fP \fP" 1c
handle surrogate splits 
.PP
.PP
 
.IP "\fBMember \fBC_splitnode\fP \fP" 1c
outplace the splitting since there are at least 3 functions with nearly identical code 
.PP
.PP
 
.IP "\fBMember \fBC_surrogates\fP \fP" 1c
enable nominal surrogate split variables as well 
.PP

