.TH "TreeGrow.c" 3 "23 Feb 2006" "party" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TreeGrow.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'party.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBC_TreeGrow\fP (SEXP node, SEXP learnsample, SEXP fitmem, SEXP controls, int *where, int *nodenum, int depth)"
.br
.ti -1c
.RI "SEXP \fBR_TreeGrow\fP (SEXP learnsample, SEXP weights, SEXP fitmem, SEXP controls, SEXP where)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The tree growing recursion
.PP
\fBAuthor:\fP
.RS 4
\fBAuthor\fP.RS 4
hothorn 
.RE
.PP
.RE
.PP
\fBDate:\fP
.RS 4
\fBDate\fP.RS 4
2006-02-14 11:35:22 +0100 (Di, 14 Feb 2006) 
.RE
.PP
.RE
.PP

.PP
Definition in file \fBTreeGrow.c\fP.
.SH "Function Documentation"
.PP 
.SS "void C_TreeGrow (SEXP node, SEXP learnsample, SEXP fitmem, SEXP controls, int * where, int * nodenum, int depth)"
.PP
The main tree growing function, handles the recursion. 
.br
 
.PP
\fBParameters:\fP
.RS 4
\fInode\fP a list representing the current node 
.br
\fIlearnsample\fP an object of class `LearningSample' 
.br
\fIfitmem\fP an object of class `TreeFitMemory' 
.br
\fIcontrols\fP an object of class `TreeControl' 
.br
\fIwhere\fP a pointer to an integer vector of n-elements 
.br
\fInodenum\fP a pointer to a integer vector of length 1 
.br
\fIdepth\fP an integer giving the depth of the current node 
.RE
.PP

.PP
Definition at line 23 of file TreeGrow.c.
.PP
References C_Node(), C_splitnode(), C_splitsurrogate(), C_surrogates(), C_TreeGrow(), check_depth(), get_maxsurrogate(), get_nobs(), get_splitctrl(), get_stump(), get_tgctrl(), S3get_leftnode(), S3get_nodeterminal(), S3get_nodeweights(), S3get_rightnode(), and S3set_nodeID().
.PP
Referenced by C_TreeGrow(), R_Ensemble(), and R_TreeGrow().
.SS "SEXP R_TreeGrow (SEXP learnsample, SEXP weights, SEXP fitmem, SEXP controls, SEXP where)"
.PP
R-interface to C_TreeGrow
.br
 
.PP
\fBParameters:\fP
.RS 4
\fIlearnsample\fP an object of class `LearningSample' 
.br
\fIweights\fP a vector of case weights 
.br
\fIfitmem\fP an object of class `TreeFitMemory' 
.br
\fIcontrols\fP an object of class `TreeControl' 
.br
\fIwhere\fP a vector of node indices for each observation 
.RE
.PP

.PP
Definition at line 80 of file TreeGrow.c.
.PP
References C_init_node(), C_TreeGrow(), get_maxsurrogate(), get_ninputs(), get_nobs(), get_splitctrl(), ncol(), NODE_LENGTH, PL2_jointtransfSym, PL2_responsesSym, and S3get_nodeweights().
.SH "Author"
.PP 
Generated automatically by Doxygen for party from the source code.
